import "./style.css";
import { io } from "socket.io-client";

const CLIENT_ID=import.meta.env.VITE_SPOTIFY_CLIENT_ID||"";
const REDIRECT_URI=new URL(import.meta.env.BASE_URL,location.origin).href;
const SERVER_URL=import.meta.env.VITE_SERVER_URL||"https://spotiguess-kk1y.onrender.com";
const API="https://api.spotify.com/v1";
const SCOPES="playlist-read-private playlist-read-collaborative user-library-read user-top-read streaming user-read-email user-read-private user-modify-playback-state user-read-playback-state";
const ROUND_MS=15000;
const FIRST_COUNTDOWN_MS=5200;

const app=document.querySelector("#app");
app.innerHTML=`
<main class="app-shell">
  <section class="screen login-screen" id="login">
    <div class="login-orbit"><div class="login-disc"><span>?</span></div></div>
    <div class="login-copy"><span class="brand-kicker">SAHURGUESS</span><h1>Quanto você conhece<br>as músicas que ama?</h1><p>Entre com o Spotify para transformar seus artistas e playlists em quizzes.</p></div>
    <button class="main-button" id="loginButton"><span class="play-icon">▶</span> Entrar com Spotify</button>
    <small class="legal">Sua senha nunca passa pelo SahurGuess.</small>
  </section>

  <section class="screen dashboard" id="dashboard">
    <header class="dash-header"><div><span class="hello">OLÁ, <b id="profileName">JOGADOR</b></span><h1>O que vamos ouvir?</h1></div><button class="avatar-button" id="profileButton" aria-label="Perfil"><img id="profileImage" alt=""></button></header>
    <div id="dashboardMessage"></div>
    <section class="shelf"><div class="section-title"><h2><span>●</span> Artistas</h2><button data-open-list="artist">Ver todos ›</button></div><div class="horizontal-cards" id="artistShelf"></div></section>
    <section class="shelf"><div class="section-title"><h2><span>☷</span> Playlists</h2><button data-open-list="playlist">Ver todas ›</button></div><div class="horizontal-cards" id="playlistShelf"></div></section>
    <button class="main-button sticky-play" id="openPlay"><span class="play-icon">▶</span> Jogar</button>
    <nav class="bottom-nav"><button class="active">⌁<span>Jogar</span></button><button id="navProfile">●<span>Você</span></button></nav>
  </section>

  <section class="screen flow-screen" id="quizType">
    <header class="flow-header"><button class="circle-back" data-back="dashboard">←</button><h2>Escolha o quiz</h2><span></span></header>
    <div class="intro-card"><h3>Como você quer jogar?</h3><p>Escolha de onde virão as músicas.</p></div>
    <div class="choice-list">
      <button data-kind="artist"><span class="choice-icon">●</span><span><b>Quiz de artista</b><small>Músicas de um artista específico</small></span><i>›</i></button>
      <button data-kind="playlist"><span class="choice-icon">☷</span><span><b>Quiz de playlist</b><small>Escolha uma das suas playlists</small></span><i>›</i></button>
      <button data-kind="liked"><span class="choice-icon">♥</span><span><b>Músicas curtidas</b><small>Quiz com as faixas que você salvou</small></span><i>›</i></button>
    </div>
  </section>

  <section class="screen flow-screen" id="sourceSelect">
    <header class="flow-header"><button class="circle-back" data-back="quizType">←</button><h2 id="sourceTitle">Escolha</h2><span></span></header>
    <div id="sourceMessage"></div><div class="source-list" id="sourceList"></div>
  </section>

  <section class="screen flow-screen" id="ready">
    <header class="flow-header"><button class="circle-back" data-back="quizType">←</button><h2>Quiz pronto</h2><span>◉</span></header>
    <div class="ready-card"><img id="readyImage" alt=""><div class="fallback-cover" id="readyFallback">♫</div><h1 id="readyTitle">Seu quiz</h1><p id="readyDescription"></p></div>
    <div class="round-block"><span>QUANTAS RODADAS?</span><div class="round-options"><button data-round="5">5</button><button class="active" data-round="10">10</button><button data-round="15">15</button><button data-round="20">20</button></div></div>
    <div id="readyMessage"></div><button class="main-button ready-play" id="readyPlay"><span class="play-icon">▶</span> Começar</button>
  </section>

  <section class="screen lobby-screen" id="lobby">
    <header class="flow-header"><button class="circle-back" id="leaveRoom">←</button><h2>Sala de jogo</h2><button class="text-button" id="lobbyLogout">Sair</button></header>
    <div class="room-code"><span>CÓDIGO DA SALA</span><strong id="roomCodeDisplay">000000</strong><small>Compartilhe com seus amigos</small></div>
    <div id="lobbyPlaylist"></div><h3 class="list-label">JOGADORES</h3><div class="players" id="players"></div><div class="grow"></div><div id="hostAction"></div>
  </section>

  <section class="screen countdown" id="countdown"><div class="count-ring"><div class="count" id="count">5</div></div><div class="count-sub" id="countSub">PREPARE-SE</div></section>

  <section class="screen game-screen" id="game">
    <header class="game-header"><button class="circle-back" id="gameExit">←</button><div><b id="gameMode">Quiz solo</b><span id="round">Faixa 1 de 10</span></div><div class="score-pill">♜ <strong id="scoreValue">0</strong></div></header>
    <div class="progress-dots" id="progressDots"></div>
    <h1>Qual é a música?</h1><div class="timer-pill">◷ <span id="timer">15.0s</span></div>
    <div class="options" id="options"></div><div class="score-float" id="scoreFloat">+0</div>
    <div class="mini-ranking" id="miniRank"></div>
  </section>

  <section class="screen final-screen" id="finalScreen">
    <header class="flow-header"><button class="circle-back" id="finalHome">←</button><h2>Fim de jogo</h2><span>◉</span></header>
    <div class="final-hero"><div class="check-badge">✓</div><h1>Quiz finalizado!</h1><p>Continue descobrindo novas músicas.</p><div class="total-card"><strong id="finalScore">0</strong><span id="finalMaximum">/ 1000</span><small>PONTOS TOTAIS</small></div></div>
    <div class="final-actions"><button class="outline-button" id="homeAgain">⌂ Início</button><button class="main-button" id="playAgain">▶ Jogar novamente</button></div>
    <section class="heard"><h2>Músicas que você ouviu</h2><div id="songHistory"></div></section>
    <section id="finalRankingWrap"><h2>Ranking final</h2><div id="finalRank"></div></section>
  </section>

  <div class="sheet-backdrop" id="sheetBackdrop" hidden></div>
  <aside class="mode-sheet" id="modeSheet" aria-hidden="true"><div class="sheet-handle"></div><header><h2>Escolha o modo</h2><button id="closeSheet">×</button></header><div class="mode-list"><button id="chooseSolo"><span>●</span><b>Quiz solo<small>Jogue rápido e supere sua pontuação</small></b><i>›</i></button><button id="chooseMulti"><span>◎</span><b>Criar sala<small>Convide amigos para jogar online</small></b><i>›</i></button></div><div class="join-box"><label>JÁ TEM UM CÓDIGO?</label><div><input id="joinCode" inputmode="numeric" maxlength="6" placeholder="000000"><button id="joinButton">Entrar</button></div><div id="joinMessage"></div></div></aside>

  <aside class="profile-sheet" id="profileSheet" aria-hidden="true"><div class="sheet-handle"></div><header><h2>Sua conta</h2><button id="closeProfile">×</button></header><div class="profile-card"><img id="profileSheetImage" alt=""><div><b id="profileSheetName">Jogador</b><small>Spotify conectado</small></div></div><label>SEU NOME NO JOGO</label><input id="playerName" maxlength="16"><button class="outline-button danger" id="logoutButton">Desconectar Spotify</button></aside>
</main>`;

const $=s=>document.querySelector(s);
const screens=["login","dashboard","quizType","sourceSelect","ready","lobby","countdown","game","finalScreen"];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const initials=s=>(s||"?").trim().slice(0,2).toUpperCase();
const shuffle=list=>[...list].sort(()=>Math.random()-.5);
const delay=ms=>new Promise(r=>setTimeout(r,ms));
function show(id){screens.forEach(x=>$("#"+x).classList.toggle("active",x===id));window.scrollTo(0,0)}
function message(el,text,type="error"){el.innerHTML=text?`<div class="${type}">${esc(text)}</div>`:""}

let tokenState=null,profile=null,playlists=[],artists=[],selectedSource=null,selectedTracks=[];
let selectedRounds=10,playMode="solo",sourceKind="playlist",name=localStorage.getItem("sahurguess_name")||"Jogador";
let socket=null,room=null,me=null,solo=false,soloState=null,countdownTimer=null,roundTimer=null,gameHistory=[];
let spotifySDKPromise=null,spotifyPlayer=null,spotifyDeviceId="",spotifyPlayerError="",spotifyCommandQueue=Promise.resolve();
let audioStartTimer=null,audioStopTimer=null,playbackNonce=0,previewAudio=null;

function hasSession(){return Boolean(sessionStorage.getItem("sp_token"))}
function rand(n=32){const a=new Uint8Array(n);crypto.getRandomValues(a);return [...a].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function pkce(){const verifier=rand(32);const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(verifier));const challenge=btoa(String.fromCharCode(...new Uint8Array(digest))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");return {verifier,challenge}}
async function spotifyLogin(){if(!CLIENT_ID)throw new Error("Client ID do Spotify não configurado.");const {verifier,challenge}=await pkce();const state=rand(16);sessionStorage.setItem("sp_pkce_verifier",verifier);sessionStorage.setItem("sp_state",state);const q=new URLSearchParams({client_id:CLIENT_ID,response_type:"code",redirect_uri:REDIRECT_URI,code_challenge_method:"S256",code_challenge:challenge,state,scope:SCOPES});location.href=`https://accounts.spotify.com/authorize?${q}`}
async function exchangeCode(code){const verifier=sessionStorage.getItem("sp_pkce_verifier");if(!verifier||new URLSearchParams(location.search).get("state")!==sessionStorage.getItem("sp_state"))throw new Error("Não foi possível validar o login.");const body=new URLSearchParams({client_id:CLIENT_ID,grant_type:"authorization_code",code,redirect_uri:REDIRECT_URI,code_verifier:verifier});const r=await fetch("https://accounts.spotify.com/api/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});if(!r.ok)throw new Error("O Spotify recusou a autorização.");const d=await r.json();tokenState={access:d.access_token,refresh:d.refresh_token,expiresAt:Date.now()+d.expires_in*1000-60000};sessionStorage.setItem("sp_token",JSON.stringify(tokenState));history.replaceState({},document.title,location.pathname)}
async function getToken(){if(tokenState?.access&&Date.now()<tokenState.expiresAt)return tokenState.access;try{tokenState=JSON.parse(sessionStorage.getItem("sp_token")||"null")}catch{tokenState=null}if(tokenState?.access&&Date.now()<tokenState.expiresAt)return tokenState.access;if(tokenState?.refresh){const body=new URLSearchParams({client_id:CLIENT_ID,grant_type:"refresh_token",refresh_token:tokenState.refresh});const r=await fetch("https://accounts.spotify.com/api/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});if(r.ok){const d=await r.json();tokenState={access:d.access_token,refresh:d.refresh_token||tokenState.refresh,expiresAt:Date.now()+d.expires_in*1000-60000};sessionStorage.setItem("sp_token",JSON.stringify(tokenState));return tokenState.access}}throw new Error("Sua sessão expirou. Entre novamente.")}
async function spotifyFetch(path,opts={}){let access=await getToken();for(let i=0;i<3;i++){const r=await fetch(API+path,{...opts,headers:{...(opts.headers||{}),Authorization:`Bearer ${access}`}});if(r.status===401){tokenState=null;sessionStorage.removeItem("sp_token");throw new Error("Sua sessão do Spotify expirou.")}if(r.status===429){await delay(Math.min(Number(r.headers.get("Retry-After")||2)*1000,8000));continue}if(!r.ok){let e={};try{e=await r.json()}catch{}throw new Error(e?.error?.message||`Erro ${r.status} do Spotify.`)}return r.status===204?null:r.json()}throw new Error("O Spotify está limitando as requisições.")}

async function loadDashboard(){message($("#dashboardMessage"),"Carregando sua biblioteca…","success");try{const [me,pls,tops]=await Promise.all([spotifyFetch("/me"),getMyPlaylists(),spotifyFetch("/me/top/artists?limit=20&time_range=medium_term").catch(()=>({items:[]}))]);profile=me;playlists=pls;artists=(tops.items||[]).map(a=>({id:a.id,name:a.name,image:a.images?.[0]?.url||"",subtitle:`${Number(a.followers?.total||0).toLocaleString("pt-BR")} seguidores`}));name=localStorage.getItem("sahurguess_name")||me.display_name||"Jogador";renderDashboard();message($("#dashboardMessage"),"")}catch(e){message($("#dashboardMessage"),e.message)}}
async function getMyPlaylists(){const out=[];let url="/me/playlists?limit=50";while(url&&out.length<100){const d=await spotifyFetch(url);out.push(...(d.items||[]).filter(Boolean).map(p=>({id:p.id,name:p.name,image:p.images?.[0]?.url||"",subtitle:`${p.tracks?.total||0} músicas`,count:p.tracks?.total||0})));url=d.next?d.next.replace(API,""):null}return out}
function renderDashboard(){const image=profile?.images?.[0]?.url||"";$("#profileName").textContent=(profile?.display_name||name).split(" ")[0].toUpperCase();$("#profileImage").src=image;$("#profileImage").style.display=image?"block":"none";$("#profileSheetImage").src=image;$("#profileSheetImage").style.display=image?"block":"none";$("#profileSheetName").textContent=profile?.display_name||name;$("#playerName").value=name;renderShelf($("#artistShelf"),artists.slice(0,10),"artist");renderShelf($("#playlistShelf"),playlists.slice(0,10),"playlist")}
function renderShelf(el,items,kind){el.innerHTML=items.length?items.map(item=>`<button class="media-card" data-id="${esc(item.id)}" data-kind="${kind}"><div>${item.image?`<img src="${esc(item.image)}" alt="">`:`<span>♫</span>`}</div><b>${esc(item.name)}</b><small>${esc(item.subtitle||"")}</small></button>`).join(""):`<div class="empty-card">Nenhum item encontrado.</div>`;el.querySelectorAll(".media-card").forEach(b=>b.onclick=()=>quickPlay(kind,b.dataset.id))}

function openSheet(){$("#sheetBackdrop").hidden=false;requestAnimationFrame(()=>$("#modeSheet").classList.add("open"));$("#modeSheet").setAttribute("aria-hidden","false")}
function closeSheet(){$("#modeSheet").classList.remove("open");$("#modeSheet").setAttribute("aria-hidden","true");setTimeout(()=>{$("#sheetBackdrop").hidden=true},250)}
function openProfile(){closeSheet();$("#sheetBackdrop").hidden=false;requestAnimationFrame(()=>$("#profileSheet").classList.add("open"));$("#profileSheet").setAttribute("aria-hidden","false")}
function closeProfile(){$("#profileSheet").classList.remove("open");$("#profileSheet").setAttribute("aria-hidden","true");setTimeout(()=>{$("#sheetBackdrop").hidden=true},250)}
function quickPlay(kind,id){const list=kind==="artist"?artists:playlists;selectedSource=list.find(x=>x.id===id)||null;sourceKind=kind;openSheet()}
function chooseMode(mode){playMode=mode;solo=mode==="solo";closeSheet();if(selectedSource){prepareSource(sourceKind,selectedSource);return}show("quizType")}

function openSourceList(kind){sourceKind=kind;if(kind==="liked"){prepareSource("liked",{id:"liked",name:"Músicas curtidas",image:"",subtitle:"Sua coleção salva"});return}const list=kind==="artist"?artists:playlists;$("#sourceTitle").textContent=kind==="artist"?"Escolha um artista":"Escolha uma playlist";$("#sourceList").innerHTML=list.map(item=>`<button class="source-row" data-id="${esc(item.id)}">${item.image?`<img src="${esc(item.image)}" alt="">`:`<span class="source-fallback">♫</span>`}<span><b>${esc(item.name)}</b><small>${esc(item.subtitle||"")}</small></span><i>›</i></button>`).join("");$("#sourceList").querySelectorAll("button").forEach(b=>b.onclick=()=>prepareSource(kind,list.find(x=>x.id===b.dataset.id)));show("sourceSelect")}
async function prepareSource(kind,source){selectedSource=source;sourceKind=kind;show("ready");message($("#readyMessage"),"Preparando músicas…","success");$("#readyTitle").textContent=source.name;$("#readyDescription").textContent=kind==="artist"?`Quiz com músicas de ${source.name}`:kind==="liked"?"Quiz com suas músicas curtidas":`Quiz baseado na playlist “${source.name}”`;$("#readyImage").src=source.image||"";$("#readyImage").style.display=source.image?"block":"none";$("#readyFallback").style.display=source.image?"none":"grid";try{selectedTracks=kind==="playlist"?(await getPlaylist(source.id)).tracks:kind==="liked"?await getLikedTracks():await getArtistTracks(source.id);if(selectedTracks.length<4)throw new Error("São necessárias pelo menos quatro músicas disponíveis.");message($("#readyMessage"),`${selectedTracks.length} músicas prontas.`,"success")}catch(e){selectedTracks=[];message($("#readyMessage"),e.message)}}
function normalizeTrack(t){return {id:t.id,name:t.name,artists:(t.artists||[]).map(a=>a.name).join(", "),album:t.album?.name||"",image:t.album?.images?.[0]?.url||"",uri:t.uri,previewUrl:t.preview_url||"",durationMs:t.duration_ms||0,spotifyUrl:t.external_urls?.spotify||""}}
async function getPlaylist(id){const meta=await spotifyFetch(`/playlists/${encodeURIComponent(id)}?fields=id,name,images,external_urls`);const items=[];let url=`/playlists/${encodeURIComponent(id)}/items?limit=50&fields=items(item(id,name,artists(id,name),album(name,images),uri,preview_url,duration_ms,type,is_local,external_urls)),next`;while(url&&items.length<200){const d=await spotifyFetch(url);for(const x of d.items||[]){if(x.item?.type==="track"&&!x.item.is_local&&x.item.id)items.push(normalizeTrack(x.item))}url=d.next?d.next.replace(API,""):null}return {...meta,tracks:items}}
async function getLikedTracks(){const items=[];let url="/me/tracks?limit=50";while(url&&items.length<200){const d=await spotifyFetch(url);for(const x of d.items||[]){if(x.track?.id)items.push(normalizeTrack(x.track))}url=d.next?d.next.replace(API,""):null}return items}
async function getArtistTracks(id){try{const d=await spotifyFetch(`/artists/${encodeURIComponent(id)}/top-tracks`);const tracks=(d.tracks||[]).filter(t=>t.id).map(normalizeTrack);if(tracks.length>=4)return tracks}catch{}const d=await spotifyFetch("/me/top/tracks?limit=50&time_range=long_term");const tracks=(d.items||[]).filter(t=>t.id&&t.artists?.some(a=>a.id===id)).map(normalizeTrack);if(tracks.length<4)throw new Error("Não encontrei músicas suficientes desse artista na sua conta.");return tracks}

function loadSpotifySDK(){if(window.Spotify)return Promise.resolve();if(spotifySDKPromise)return spotifySDKPromise;spotifySDKPromise=new Promise((resolve,reject)=>{const script=document.createElement("script");script.src="https://sdk.scdn.co/spotify-player.js";script.async=true;window.onSpotifyWebPlaybackSDKReady=resolve;script.onerror=()=>reject(new Error("Falha ao carregar o player."));document.head.appendChild(script);setTimeout(()=>reject(new Error("O player demorou demais para responder.")),15000)});return spotifySDKPromise}
async function ensureSpotifyPlayer(){if(spotifyPlayer&&spotifyDeviceId)return true;try{await loadSpotifySDK();await getToken();const player=new window.Spotify.Player({name:"SahurGuess",getOAuthToken:cb=>getToken().then(cb).catch(()=>cb("")),volume:.8});spotifyPlayer=player;const ready=new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error("O player não ficou pronto.")),15000);player.addListener("ready",({device_id})=>{clearTimeout(timeout);spotifyDeviceId=device_id;resolve(true)});player.addListener("not_ready",()=>spotifyDeviceId="");const fail=m=>{clearTimeout(timeout);reject(new Error(m))};player.addListener("initialization_error",({message})=>fail(message));player.addListener("authentication_error",({message})=>fail(message));player.addListener("account_error",()=>fail("Esta conta precisa ser Spotify Premium."));player.addListener("autoplay_failed",()=>spotifyPlayerError="Toque novamente em começar para liberar o áudio.")});if(!await player.connect())return false;if(player.activateElement)player.activateElement();await ready;return true}catch(e){spotifyPlayerError=e?.message||"Não foi possível iniciar o player.";return false}}
async function pausePlayback(){if(!spotifyDeviceId)return;const command=spotifyCommandQueue.catch(()=>{}).then(()=>spotifyPlayer?.pause());spotifyCommandQueue=command.catch(()=>{});try{await command}catch{}}
function stopAudio(){playbackNonce++;clearTimeout(audioStartTimer);clearTimeout(audioStopTimer);audioStartTimer=null;audioStopTimer=null;if(previewAudio){previewAudio.pause();previewAudio.src="";previewAudio=null}pausePlayback()}
async function playTrack(track,positionMs=null,stopAt=null){const nonce=++playbackNonce;if(!track?.uri)return;const ready=await ensureSpotifyPlayer();if(!ready||nonce!==playbackNonce)return;const maxStart=Math.max(0,(Number(track.durationMs)||30000)-ROUND_MS);const position=Number.isFinite(positionMs)?Math.min(positionMs,maxStart):Math.floor(Math.random()*(maxStart+1));const command=spotifyCommandQueue.catch(()=>{}).then(async()=>{if(nonce!==playbackNonce)return false;if(spotifyPlayer)await spotifyPlayer.pause();if(nonce!==playbackNonce)return false;await spotifyFetch(`/me/player/play?device_id=${encodeURIComponent(spotifyDeviceId)}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({uris:[track.uri],position_ms:position})});return nonce===playbackNonce});spotifyCommandQueue=command.catch(()=>{});try{if(!await command)return;const remaining=Number.isFinite(stopAt)?Math.max(0,stopAt-Date.now()):ROUND_MS;audioStopTimer=setTimeout(()=>{if(nonce===playbackNonce)pausePlayback()},remaining)}catch(e){spotifyPlayerError=e.message}}

function buildQuestion(tracks,used){let pool=tracks.filter(t=>!used.has(t.id));if(!pool.length){used.clear();pool=[...tracks]}const correct=pool[Math.floor(Math.random()*pool.length)];used.add(correct.id);const all=shuffle([correct,...shuffle(tracks.filter(t=>t.id!==correct.id)).slice(0,3)]);return {correct,options:all.map((t,i)=>({id:String(i),label:t.name})),correctId:String(all.findIndex(t=>t.id===correct.id))}}
async function beginReady(){if(selectedTracks.length<4){message($("#readyMessage"),"Aguarde as músicas terminarem de carregar.");return}message($("#readyMessage"),"Ativando seu player…","success");if(!await ensureSpotifyPlayer()){message($("#readyMessage"),spotifyPlayerError);return}gameHistory=[];if(playMode==="solo")startSolo();else createRoom()}
function startSolo(){solo=true;me="solo";room={code:"SOLO",hostId:me,round:0,totalRounds:Math.min(selectedRounds,selectedTracks.length),playlist:{name:selectedSource.name,image:selectedSource.image},players:[{id:me,name,score:0,streak:0}],finalRanking:[]};soloState={tracks:selectedTracks.slice(0,200),used:new Set(),current:null,answered:false};startCountdown(1,FIRST_COUNTDOWN_MS,()=>startSoloRound(1))}
function startCountdown(round,ms,next){stopAudio();const at=Date.now()+ms;show("countdown");clearInterval(countdownTimer);const tick=()=>{const left=at-Date.now();$("#count").textContent=Math.max(1,Math.ceil(left/1000));$("#countSub").textContent=`RODADA ${round} DE ${room.totalRounds}`;if(left<=0){clearInterval(countdownTimer);next?.()}};tick();countdownTimer=setInterval(tick,60)}
function startSoloRound(round){const q=buildQuestion(soloState.tracks,soloState.used);const startedAt=Date.now()+1200,endsAt=startedAt+ROUND_MS;room.round=round;room.current={round,startedAt,endsAt,options:q.options};soloState.current={...q,round,startedAt,endsAt};soloState.answered=false;renderRound({round,totalRounds:room.totalRounds,startedAt,endsAt,options:q.options});audioStartTimer=setTimeout(()=>playTrack(q.correct,null,endsAt),Math.max(0,startedAt-Date.now()-650))}
function renderRound(d){show("game");$("#gameMode").textContent=solo?"Quiz solo":"Quiz multiplayer";$("#round").textContent=`Faixa ${d.round} de ${d.totalRounds}`;$("#scoreValue").textContent=(room.players.find(p=>p.id===me)?.score||0);$("#progressDots").innerHTML=Array.from({length:d.totalRounds},(_,i)=>`<span class="${i<gameHistory.length?(gameHistory[i]?.correct?"correct":"wrong"):i===d.round-1?"current":""}"></span>`).join("");$("#options").innerHTML=d.options.map((o,i)=>`<button class="option" data-id="${o.id}"><span>${"ABCD"[i]}</span><b>${esc(o.label)}</b></button>`).join("");$("#options").querySelectorAll("button").forEach(b=>b.onclick=()=>submitAnswer(d,b));$("#scoreFloat").classList.remove("show");clearInterval(roundTimer);const tick=()=>{const now=Date.now();const left=now<d.startedAt?ROUND_MS:Math.max(0,d.endsAt-now);$("#timer").textContent=`${(left/1000).toFixed(1)}s`;const disabled=now<d.startedAt;$("#options").querySelectorAll("button").forEach(b=>{if(!b.classList.contains("answered"))b.disabled=disabled});if(left<=0){clearInterval(roundTimer);if(solo)finishSolo(null)}};tick();roundTimer=setInterval(tick,50);renderMiniRank()}
function submitAnswer(d,button){if(button.disabled)return;$("#options").querySelectorAll("button").forEach(x=>{x.disabled=true;x.classList.add("answered")});button.classList.add("selected");if(solo)finishSolo(button.dataset.id);else socket.emit("answer",{code:room.code,round:d.round,optionId:button.dataset.id},res=>{if(!res?.ok)alert(res?.error||"Resposta não enviada")})}
function finishSolo(optionId){if(!soloState?.current||soloState.answered)return;soloState.answered=true;clearInterval(roundTimer);stopAudio();const q=soloState.current,p=room.players[0],correct=optionId===q.correctId;const elapsed=Math.max(0,Math.min(ROUND_MS,Date.now()-q.startedAt));const delta=correct?Math.max(0,Math.round(100*(1-elapsed/ROUND_MS))):0;p.score+=delta;const history={...q.correct,correct,delta,positionMs:null};gameHistory.push(history);$("#scoreValue").textContent=p.score;const selected=$("#options [data-id='${optionId}']");if(selected)selected.classList.add(correct?"correct":"wrong");const right=$("#options [data-id='${q.correctId}']");right?.classList.add("correct");$("#scoreFloat").textContent=correct?`+${delta}`:"Errou";$("#scoreFloat").classList.add("show");setTimeout(()=>{if(room.round>=room.totalRounds){room.finalRanking=[{id:me,name,score:p.score}];showFinal(room)}else startSoloRound(room.round+1)},850)}
function renderMiniRank(){const el=$("#miniRank");if(solo){el.innerHTML="";return}const sorted=[...(room?.players||[])].sort((a,b)=>b.score-a.score);el.innerHTML=sorted.slice(0,4).map((p,i)=>`<div><span>#${i+1} ${esc(p.name)}</span><b>${p.score}</b></div>`).join("")}

function connectSocket(){if(socket?.connected)return;socket=io(SERVER_URL,{transports:["websocket","polling"]});socket.on("room:update",r=>{room=r;renderLobby()});socket.on("room:countdown",d=>startCountdown(d.round,Math.max(0,d.at-Date.now())));socket.on("room:round",d=>{room.round=d.round;room.current=d;renderRound(d)});socket.on("room:track",d=>{audioStartTimer=setTimeout(()=>playTrack(d.track,d.positionMs,d.endsAt),Math.max(0,d.startedAt-Date.now()-650))});socket.on("room:result",r=>{stopAudio();room=r;recordMultiResult(r);showMultiResult(r)});socket.on("room:finished",r=>{stopAudio();room=r;showFinal(r)});socket.on("room:closed",d=>{alert(d.message);goHome()})}
function createRoom(){solo=false;connectSocket();socket.emit("room:create",{name,playlist:selectedSource,tracks:selectedTracks,totalRounds:selectedRounds},res=>{if(!res?.ok){message($("#readyMessage"),res?.error||"Não foi possível criar a sala.");return}room=res.room;me=res.playerId;show("lobby");renderLobby()})}
async function joinRoom(){const code=$("#joinCode").value.replace(/\D/g,"");if(code.length!==6){message($("#joinMessage"),"Digite os 6 números.");return}$("#joinButton").disabled=true;$("#joinButton").textContent="Ativando…";if(!await ensureSpotifyPlayer()){message($("#joinMessage"),spotifyPlayerError);$("#joinButton").disabled=false;$("#joinButton").textContent="Entrar";return}solo=false;closeSheet();connectSocket();socket.emit("room:join",{code,name},res=>{if(!res?.ok){openSheet();message($("#joinMessage"),res?.error||"Sala não encontrada.");$("#joinButton").disabled=false;$("#joinButton").textContent="Entrar";return}room=res.room;me=res.playerId;show("lobby");renderLobby()})}
function renderLobby(){if(!room)return;$("#roomCodeDisplay").textContent=room.code;$("#lobbyPlaylist").innerHTML=`<div class="selected-summary">${room.playlist.image?`<img src="${esc(room.playlist.image)}" alt="">`:""}<div><small>QUIZ SELECIONADO</small><b>${esc(room.playlist.name)}</b><span>${room.totalRounds} rodadas</span></div></div>`;$("#players").innerHTML=room.players.map(p=>`<div class="player"><span>${esc(initials(p.name))}</span><b>${esc(p.name)}${p.id===me?" (você)":""}</b>${p.id===room.hostId?"<i>HOST</i>":""}</div>`).join("");$("#hostAction").innerHTML=room.hostId===me?`<button class="main-button" id="startRoom">▶ Iniciar jogo</button>`:`<p class="waiting">Aguardando o host iniciar…</p>`;$("#startRoom")?.addEventListener("click",()=>socket.emit("room:start",{code:room.code},res=>{if(!res?.ok)alert(res.error)}))}
function recordMultiResult(r){const mine=r.results?.results?.find(x=>x.id===me);gameHistory.push({...r.results.track,correct:Boolean(mine?.correct),delta:mine?.delta||0})}
function showMultiResult(r){const mine=r.results?.results?.find(x=>x.id===me);if(mine)$("#scoreValue").textContent=mine.score;$("#scoreFloat").textContent=mine?.correct?`+${mine.delta}`:"Errou";$("#scoreFloat").classList.add("show");const right=$("#options [data-id='${r.results?.correctId}']");right?.classList.add("correct");renderMiniRank()}
function showFinal(r){clearInterval(roundTimer);show("finalScreen");const score=(r.players||[]).find(p=>p.id===me)?.score||r.finalRanking?.find(p=>p.id===me)?.score||0;$("#finalScore").textContent=score;$("#finalMaximum").textContent=`/ ${r.totalRounds*100}`;$("#songHistory").innerHTML=gameHistory.map((t,i)=>`<article class="song-row"><strong class="answer-mark ${t.correct?"yes":"no"}">${t.correct?"✓":"×"}</strong>${t.image?`<img src="${esc(t.image)}" alt="">`:`<span class="song-cover">♫</span>`}<div><b>${esc(t.name)}</b><small>${esc(t.artists)}</small></div><button data-replay="${i}" aria-label="Tocar novamente">▶</button></article>`).join("");$("#songHistory").querySelectorAll("[data-replay]").forEach(b=>b.onclick=()=>playTrack(gameHistory[Number(b.dataset.replay)]));const ranking=r.finalRanking||[];$("#finalRankingWrap").style.display=solo?"none":"block";$("#finalRank").innerHTML=ranking.map((p,i)=>`<div class="rank-row"><span>#${i+1}</span><b>${esc(p.name)}</b><strong>${p.score}</strong></div>`).join("")}

function logout(){stopAudio();if(room&&socket)socket.emit("room:leave",{code:room.code});try{spotifyPlayer?.disconnect()}catch{}["sp_token","sp_pkce_verifier","sp_state","sp_after_auth"].forEach(k=>sessionStorage.removeItem(k));location.reload()}
function leave(){stopAudio();if(room&&socket)socket.emit("room:leave",{code:room.code});room=null;me=null;goHome()}
function goHome(){stopAudio();selectedSource=null;selectedTracks=[];gameHistory=[];show("dashboard")}

$("#loginButton").onclick=()=>spotifyLogin().catch(e=>alert(e.message));$("#openPlay").onclick=()=>{selectedSource=null;openSheet()};$("#closeSheet").onclick=closeSheet;$("#sheetBackdrop").onclick=()=>{$("#profileSheet").classList.contains("open")?closeProfile():closeSheet()};$("#chooseSolo").onclick=()=>chooseMode("solo");$("#chooseMulti").onclick=()=>chooseMode("multi");$("#joinButton").onclick=joinRoom;$("#joinCode").oninput=e=>e.target.value=e.target.value.replace(/\D/g,"").slice(0,6);$("#profileButton").onclick=openProfile;$("#navProfile").onclick=openProfile;$("#closeProfile").onclick=closeProfile;$("#logoutButton").onclick=logout;$("#playerName").oninput=e=>{name=e.target.value.slice(0,16)||"Jogador";localStorage.setItem("sahurguess_name",name)};document.querySelectorAll("[data-open-list]").forEach(b=>b.onclick=()=>{playMode="solo";solo=true;openSourceList(b.dataset.openList)});document.querySelectorAll("[data-kind]").forEach(b=>b.onclick=()=>openSourceList(b.dataset.kind));document.querySelectorAll("[data-back]").forEach(b=>b.onclick=()=>show(b.dataset.back));document.querySelectorAll("[data-round]").forEach(b=>b.onclick=()=>{selectedRounds=Number(b.dataset.round);document.querySelectorAll("[data-round]").forEach(x=>x.classList.toggle("active",x===b))});$("#readyPlay").onclick=beginReady;$("#leaveRoom").onclick=leave;$("#lobbyLogout").onclick=logout;$("#gameExit").onclick=leave;$("#finalHome").onclick=goHome;$("#homeAgain").onclick=goHome;$("#playAgain").onclick=()=>{if(selectedSource&&selectedTracks.length)show("ready");else goHome()};

(async()=>{const params=new URLSearchParams(location.search);if(params.get("code")&&sessionStorage.getItem("sp_pkce_verifier")){try{await exchangeCode(params.get("code"))}catch(e){sessionStorage.clear();show("login");alert(e.message);return}}if(!hasSession()){show("login");return}show("dashboard");await loadDashboard()})();
